const { success } = require('../middlewares/response');
const { asyncHandler } = require('../middlewares/asyncHandler');
const service = require('../services/customerService');
const list = asyncHandler(async (req, res) => { const result = await service.listCustomers(req.user, req.query); return success(res, { message: 'Lấy danh sách khách hàng thành công.', data: result.customers, meta: result.meta }); });
const get = asyncHandler(async (req, res) => success(res, { message: 'Lấy hồ sơ khách hàng thành công.', data: await service.getCustomer(req.user, req.params.id) }));
const create = asyncHandler(async (req, res) => success(res, { status: 201, message: 'Tạo khách hàng thành công.', data: await service.createCustomer(req.user, req.body) }));
const update = asyncHandler(async (req, res) => success(res, { message: 'Cập nhật khách hàng thành công.', data: await service.updateCustomer(req.user, req.params.id, req.body) }));
const remove = asyncHandler(async (req, res) => { await service.deleteCustomer(req.user, req.params.id); return success(res, { message: 'Xóa khách hàng và toàn bộ dữ liệu liên quan thành công.', data: null }); });
const createPackage = asyncHandler(async (req, res) => success(res, { status: 201, message: 'Tạo gói PT thành công.', data: await service.createPackage(req.user, req.params.id, req.body) }));
const updatePackage = asyncHandler(async (req, res) => success(res, { message: 'Cập nhật gói PT thành công.', data: await service.updatePackage(req.user, req.params.id, req.params.packageId, req.body) }));
const deletePackage = asyncHandler(async (req, res) => { await service.deletePackage(req.user, req.params.id, req.params.packageId); return success(res, { message: 'Xóa gói PT thành công.', data: null }); });
const listPackages = asyncHandler(async (req, res) => { const result = await service.listPackages(req.user, req.params.id, req.query); return success(res, { message: 'Lấy danh sách gói PT thành công.', data: result.packages, meta: result.meta }); });
const createAccount = asyncHandler(async (req, res) => success(res, { status: 201, message: 'Cấp tài khoản khách hàng thành công.', data: await service.createCustomerAccount(req.user, req.params.id, req.body) }));
module.exports = { list, get, create, update, remove, createPackage, updatePackage, deletePackage, listPackages, createAccount };
