const { success } = require('../middlewares/response');
const { asyncHandler } = require('../middlewares/asyncHandler');
const service = require('../services/transferService');
const create = asyncHandler(async (req, res) => success(res, { status: 201, message: 'Gửi yêu cầu chuyển PT thành công.', data: await service.createTransfer(req.user, req.body) }));
const update = asyncHandler(async (req, res) => success(res, { message: 'Cập nhật yêu cầu chuyển PT thành công.', data: await service.updateTransfer(req.user, req.params.id, req.body) }));
const remove = asyncHandler(async (req, res) => { await service.deleteTransfer(req.user, req.params.id); return success(res, { message: 'Xóa yêu cầu chuyển PT thành công.', data: null }); });
const accept = asyncHandler(async (req, res) => success(res, { message: 'Xác nhận nhận khách thành công.', data: await service.resolveTransfer(req.user, req.params.id, 'accept') }));
const reject = asyncHandler(async (req, res) => success(res, { message: 'Từ chối nhận khách thành công.', data: await service.resolveTransfer(req.user, req.params.id, 'reject') }));
const force = asyncHandler(async (req, res) => success(res, { message: 'Admin chuyển khách thành công.', data: await service.forceTransfer(req.user, req.params.id, req.body) }));
const list = asyncHandler(async (req, res) => { const result = await service.listTransfers(req.user, req.query); return success(res, { message: 'Lấy danh sách yêu cầu chuyển PT thành công.', data: result.items, meta: result.meta }); });
module.exports = { create, update, remove, accept, reject, force, list };
