services:
  3s-gym:
    image: ghcr.io/chung2310/3s-gym:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-3s-gym}
    restart: always
    ports:
      - "${PORT:-3008}:${PORT:-3008}"
    env_file:
      - .env
    volumes:
      - .env:/app/.env
      - ./uploads:/app/uploads
    networks:
      - default_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db-migrate:
    image: ghcr.io/chung2310/3s-gym:${IMAGE_TAG:-latest}
    env_file:
      - .env
    entrypoint: ["node", "dist/backend/scripts/migrate.js", "up"]
    profiles:
      - migration
    networks:
      - default_network

networks:
  default_network:
    external: true
