import type { TrackingPrescription, TrackingType } from '../../../types';

interface Props { exerciseName: string; trackingType: TrackingType; value: TrackingPrescription; onChange: (value: TrackingPrescription) => void; disabled?: boolean }
const inputClass = 'min-h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none focus-visible:border-secondary focus-visible:ring-2 focus-visible:ring-secondary/20';

export default function PrescriptionEditor({ exerciseName, trackingType, value, onChange, disabled }: Props) {
  const data = value as Record<string, unknown>;
  const set = (field: string, raw: string, text = false) => onChange({ ...data, [field]: raw === '' ? undefined : text ? raw : Number(raw) } as TrackingPrescription);
  const field = (label: string, key: string, options: { text?: boolean; min?: number; max?: number } = {}) => <label className="grid gap-1 text-xs font-semibold text-slate-600"><span>{label}</span><input className={inputClass} aria-label={`${label} cho ${exerciseName}`} placeholder={options.text ? 'Ví dụ: 8-12' : '0'} type={options.text ? 'text' : 'number'} min={options.min ?? 0} max={options.max} value={String(data[key] ?? '')} disabled={disabled} onChange={(event) => set(key, event.target.value, options.text)} /></label>;
  if (trackingType === 'UNCLASSIFIED') return <p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs font-semibold text-amber-800">{exerciseName} chưa có cách ghi nhận.</p>;
  if (trackingType === 'STRENGTH') return <div className="grid gap-2 sm:grid-cols-3">{field('Sets', 'sets', { min: 1 })}{field('Reps', 'reps', { text: true })}{field('Weight (kg)', 'targetWeight')}{field('Target RPE', 'targetRpe', { max: 10 })}{field('Target RIR', 'targetRir')}{field('Rest (giây)', 'restSeconds')}</div>;
  if (trackingType === 'BODYWEIGHT') return <div className="grid gap-2 sm:grid-cols-3">{field('Sets', 'sets', { min: 1 })}{field('Reps', 'reps', { text: true })}{field('Added Weight (kg)', 'addedWeight')}{field('Target RPE', 'targetRpe', { max: 10 })}{field('Target RIR', 'targetRir')}{field('Rest (giây)', 'restSeconds')}</div>;
  if (trackingType === 'CARDIO') return <div className="grid gap-2 sm:grid-cols-3">{field('Duration (phút)', 'durationMinutes', { min: 1 })}{field('Distance (km)', 'distanceKm')}{field('Target Pace (s/km)', 'targetPaceSecondsPerKm', { min: 1 })}{field('Target HR (bpm)', 'targetHeartRate', { min: 1 })}{field('Incline (%)', 'inclinePercent')}{field('Target RPE', 'targetRpe', { max: 10 })}</div>;
  if (trackingType === 'INTERVAL') return <div className="grid gap-2 sm:grid-cols-3">{field('Rounds', 'rounds', { min: 1 })}{field('Work (giây)', 'workSeconds', { min: 1 })}{field('Rest (giây)', 'restSeconds')}{field('Distance/Round (m)', 'distanceMetersPerRound', { min: 1 })}{field('Reps/Round', 'repsPerRound', { min: 1 })}{field('Target RPE', 'targetRpe', { max: 10 })}</div>;
  return <div className="grid gap-2 sm:grid-cols-3">{field('Duration (phút)', 'durationMinutes', { min: 1 })}{field('Reps', 'reps', { min: 1 })}<label className="grid gap-1 text-xs font-semibold text-slate-600"><span>Side</span><select className={inputClass} aria-label={`Bên tập cho ${exerciseName}`} value={String(data.side ?? 'BOTH')} disabled={disabled} onChange={(event) => set('side', event.target.value, true)}><option value="BOTH">Hai bên</option><option value="LEFT">Trái</option><option value="RIGHT">Phải</option></select></label>{field('Target Discomfort (1-10)', 'targetDiscomfort', { max: 10 })}</div>;
}
