import { useState } from 'react';
import { api } from '../../services/api';
import { errorMessage } from '../../types';

type Customer = { _id: string; fullName: string; phone: string };
type Proposal = { durationWeeks: number; sessionsPerWeek: number; minutesPerSession: number; level: string; trainingMethod: string; trainingSplit: string; priorityMuscleGroups: string[]; restrictions: string[] };
type Props = { open: boolean; customers: Customer[]; onClose(): void; onGenerated(value: unknown): void };

export default function AiWorkoutWizard({ open, customers, onClose, onGenerated }: Props) {
  const [customerId, setCustomerId] = useState(''); const [proposal, setProposal] = useState<Proposal>(); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  if (!open) return null;
  const analyze = async () => { if (!customerId) return setError('Vui lòng chọn học viên.'); setLoading(true); setError(''); try { const result = await api.post<Proposal>('/api/ai/workout-proposals', { customerId }); setProposal(result.data); } catch (cause) { setError(errorMessage(cause)); } finally { setLoading(false); } };
  const generate = async () => { if (!proposal) return; setLoading(true); setError(''); try { const result = await api.post('/api/ai/workout-generations', { customerId, proposal, additionalRequest: '' }); onGenerated(result.data); } catch (cause) { setError(errorMessage(cause)); } finally { setLoading(false); } };
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Tạo giáo án bằng AI"><div className="modal-content ai-workout-wizard"><div className="modal-header"><h2>Tạo giáo án bằng AI</h2><button type="button" className="modal-close" aria-label="Đóng" onClick={onClose}>×</button></div><div className="panel"><span className="badge-tag">{proposal ? 'Bước 2 · Duyệt đề xuất' : 'Bước 1 · Chọn học viên'}</span>{!proposal ? <div className="form-grid"><label className="form-group">Học viên<select aria-label="Học viên" value={customerId} onChange={(event) => setCustomerId(event.target.value)}><option value="">Chọn học viên...</option>{customers.map((customer) => <option key={customer._id} value={customer._id}>{customer.fullName} · {customer.phone}</option>)}</select></label></div> : <div className="form-grid"><label className="form-group">Số tuần<input aria-label="Số tuần" type="number" value={proposal.durationWeeks} onChange={(event) => setProposal({ ...proposal, durationWeeks: Number(event.target.value) })} /></label><label className="form-group">Số buổi mỗi tuần<input aria-label="Số buổi mỗi tuần" type="number" value={proposal.sessionsPerWeek} onChange={(event) => setProposal({ ...proposal, sessionsPerWeek: Number(event.target.value) })} /></label><label className="form-group">Số phút mỗi buổi<input aria-label="Số phút mỗi buổi" type="number" value={proposal.minutesPerSession} onChange={(event) => setProposal({ ...proposal, minutesPerSession: Number(event.target.value) })} /></label></div>}{error && <p className="empty-state">{error}</p>}</div><div className="modal-actions"><button type="button" className="button button-secondary" onClick={onClose}>Hủy</button><button type="button" className="button button-primary" disabled={loading} onClick={proposal ? generate : analyze}>{loading ? 'Đang xử lý...' : proposal ? 'Tạo giáo án' : 'Phân tích bằng AI'}</button></div></div></div>;
}
