import type { CardioPrescription, CardioResult } from '../../../types';
import TrackingNumberField from './TrackingNumberField';

interface Props { exerciseName: string; prescription: CardioPrescription; value: CardioResult; onChange: (value: CardioResult) => void }

export default function CardioResultEditor({ exerciseName, prescription, value, onChange }: Props) {
  const set = (field: keyof CardioResult, next?: number) => onChange({ ...(value || {}), [field]: next });
  return <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><TrackingNumberField label="Thời lượng (phút)" ariaLabel={`${exerciseName} thời lượng (phút)`} value={value?.durationMinutes} placeholder={prescription?.durationMinutes} onChange={(next) => set('durationMinutes', next)} /><TrackingNumberField label="Quãng đường (km)" ariaLabel={`${exerciseName} quãng đường (km)`} value={value?.distanceKm} placeholder={prescription?.distanceKm} step="0.01" onChange={(next) => set('distanceKm', next)} /><TrackingNumberField label="Pace (giây/km)" ariaLabel={`${exerciseName} pace (giây/km)`} value={value?.paceSecondsPerKm} placeholder={prescription?.targetPaceSecondsPerKm} onChange={(next) => set('paceSecondsPerKm', next)} /><TrackingNumberField label="Nhịp tim trung bình" ariaLabel={`${exerciseName} nhịp tim trung bình`} value={value?.averageHeartRate} placeholder={prescription?.targetHeartRate} onChange={(next) => set('averageHeartRate', next)} /><TrackingNumberField label="Độ dốc (%)" ariaLabel={`${exerciseName} độ dốc (%)`} value={value?.inclinePercent} placeholder={prescription?.inclinePercent} step="0.1" onChange={(next) => set('inclinePercent', next)} /><TrackingNumberField label="Calories" ariaLabel={`${exerciseName} calories`} value={value?.calories} onChange={(next) => set('calories', next)} /><TrackingNumberField label="RPE" ariaLabel={`${exerciseName} RPE`} value={value?.rpe} placeholder={prescription?.targetRpe} max={10} step="0.1" onChange={(next) => set('rpe', next)} /></div>;
}
