import { useCallback, useEffect, useRef, useState } from 'react';
import { CheckCircle2, Clock3, LoaderCircle, RefreshCw, XCircle } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useCreditWallet } from '../../contexts/CreditWalletContext';
import { creditsService } from '../../services/credits';
import type { PaymentOrder } from '../../types/credits';
export default function PaymentResultPage() {
  const [params] = useSearchParams(); const orderId = params.get('orderId') || window.sessionStorage.getItem('3s:pending-credit-order-id') || ''; const { refresh } = useCreditWallet();
  const [order, setOrder] = useState<PaymentOrder | null>(null); const [error, setError] = useState(''); const [timedOut, setTimedOut] = useState(false); const started = useRef(Date.now());
  const read = useCallback(async () => { if (!orderId) { setError('Thiếu mã đơn thanh toán.'); return false; } try { const next = await creditsService.order(orderId); setOrder(next); setError(''); if (next.status === 'PAID') { window.sessionStorage.removeItem('3s:pending-credit-order-id'); await refresh(); } return next.status === 'PENDING'; } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể kiểm tra đơn thanh toán.'); return false; } }, [orderId, refresh]);
  useEffect(() => { let active = true; let timer: number | undefined; const poll = async () => { const pending = await read(); if (!active || !pending) return; if (Date.now() - started.current >= 60_000) { setTimedOut(true); return; } timer = window.setTimeout(poll, 2_000); }; void poll(); return () => { active = false; window.clearTimeout(timer); }; }, [read]);
  const status = order?.status; const Icon = status === 'PAID' ? CheckCircle2 : status === 'FAILED' || status === 'EXPIRED' ? XCircle : Clock3;
  return <div className="mx-auto max-w-xl rounded-3xl border border-slate-200 bg-white p-7 text-center shadow-xl shadow-slate-200/50"><Icon className={`mx-auto ${status === 'PAID' ? 'text-emerald-500' : status === 'FAILED' || status === 'EXPIRED' ? 'text-rose-500' : 'text-amber-500'}`} size={52} /><h1 className="mt-5 text-2xl font-black text-slate-900">{status === 'PAID' ? 'Nạp credit thành công' : status === 'FAILED' ? 'Thanh toán thất bại' : status === 'EXPIRED' ? 'Đơn đã hết hạn' : 'Đang xác nhận thanh toán'}</h1>{!order && !error && <LoaderCircle className="mx-auto mt-4 animate-spin text-secondary" />}{order && <p className="mt-3 text-sm text-slate-500">Đơn {order.orderCode} · {order.grantCredits} credit</p>}{error && <p role="alert" className="mt-4 text-sm text-rose-600">{error}</p>}{timedOut && <p className="mt-4 text-sm text-amber-700">Chưa nhận được xác nhận sau 60 giây. Bạn có thể kiểm tra lại thủ công.</p>}<div className="mt-6 flex justify-center gap-3">{(timedOut || error) && <button type="button" onClick={() => { setTimedOut(false); started.current = Date.now(); void read(); }} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-4 py-2 font-bold text-slate-700"><RefreshCw size={16} /> Kiểm tra lại</button>}<Link to="/wallet" className="rounded-xl bg-primary px-4 py-2 font-bold text-white">Về ví credit</Link></div></div>;
}
