import { useEffect, useMemo, useState } from 'react';
import { CreditCard, History, LoaderCircle, ShieldCheck, WalletCards } from 'lucide-react';
import CreditLedgerTable from '../../components/credits/CreditLedgerTable';
import CreditPackageGrid from '../../components/credits/CreditPackageGrid';
import CustomTopupForm from '../../components/credits/CustomTopupForm';
import Pagination from '../../components/ui/Pagination';
import { useToast } from '../../components/ui/ToastProvider';
import { useCreditWallet } from '../../contexts/CreditWalletContext';
import { creditsService } from '../../services/credits';
import { errorMessage } from '../../types';
import type { CreditLedgerEntry, CreditPackageResponse, PaymentGateway } from '../../types/credits';

export default function WalletPage() {
  const { wallet, loading: walletLoading } = useCreditWallet(); const toast = useToast();
  const [catalog, setCatalog] = useState<CreditPackageResponse | null>(null); const [entries, setEntries] = useState<CreditLedgerEntry[]>([]);
  const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [type, setType] = useState('');
  const [selectedId, setSelectedId] = useState(''); const [custom, setCustom] = useState(''); const [customSelected, setCustomSelected] = useState(false); const [gateway, setGateway] = useState<PaymentGateway>('VNPAY');
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const loadLedger = async (nextPage = page, nextType = type) => { const result = await creditsService.ledger(nextPage, nextType); setEntries(result.items); setTotalPages(result.meta?.totalPages || 1); };
  useEffect(() => { let active = true; Promise.all([creditsService.packages(), creditsService.ledger(1)]).then(([nextCatalog, ledger]) => { if (!active) return; setCatalog(nextCatalog); setEntries(ledger.items); setTotalPages(ledger.meta?.totalPages || 1); const first = (['VNPAY', 'MOMO'] as const).find((item) => nextCatalog.gateways[item]); if (first) setGateway(first); }).catch((cause) => active && setError(errorMessage(cause))).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);
  const customAmount = Number(custom); const customValid = Number.isInteger(customAmount) && customAmount >= 10_000 && customAmount <= 50_000_000 && customAmount % 1_000 === 0;
  const canSubmit = Boolean(catalog?.gateways[gateway]) && (customSelected ? customValid : Boolean(selectedId)) && !submitting;
  const estimated = useMemo(() => customSelected && customValid ? Math.floor(customAmount / 1_000) : catalog?.packages.find((item) => item.id === selectedId)?.grantCredits || 0, [catalog, customAmount, customSelected, customValid, selectedId]);
  const checkout = async () => { if (!canSubmit) return; setSubmitting(true); try { const order = await creditsService.createTopup(customSelected ? { gateway, customAmountVnd: customAmount } : { gateway, packageId: selectedId }); const url = new URL(order.redirectUrl || '', window.location.origin); const allowed = url.protocol === 'https:' || (url.protocol === 'http:' && ['localhost', '127.0.0.1'].includes(url.hostname)); if (!allowed) throw new Error('Liên kết thanh toán không an toàn.'); window.sessionStorage.setItem('3s:pending-credit-order-id', order.id); window.location.assign(url.toString()); } catch (cause) { toast.error(errorMessage(cause)); setSubmitting(false); } };
  if (loading) return <div className="space-y-4" aria-label="Đang tải ví credit"><div className="h-36 animate-pulse rounded-3xl bg-slate-200" /><div className="grid gap-3 sm:grid-cols-3">{[1, 2, 3].map((item) => <div key={item} className="h-44 animate-pulse rounded-2xl bg-slate-200" />)}</div></div>;
  if (error) return <div role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-rose-700">{error}</div>;
  return <div className="mx-auto max-w-6xl space-y-8 font-montserrat"><section className="overflow-hidden rounded-3xl bg-primary p-6 text-white shadow-xl shadow-blue-950/10 sm:p-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><span className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.22em] text-sky-200"><WalletCards size={17} /> Ví AI 3S Gym</span><p className="mt-5 text-sm text-sky-100">Credit khả dụng</p><strong className="mt-1 block text-5xl font-black">{walletLoading ? '…' : wallet?.availableCredits ?? 0}</strong></div><div className="rounded-2xl border border-white/15 bg-white/10 px-5 py-4"><span className="text-xs uppercase tracking-wider text-sky-200">Đang tạm giữ</span><strong className="mt-1 block text-2xl">{wallet?.reservedCredits ?? 0} credit</strong></div></div></section>
    <section className="space-y-5 rounded-3xl border border-slate-200 bg-white p-5 sm:p-7"><div><h1 className="text-2xl font-black text-slate-900">Nạp credit</h1><p className="mt-1 text-sm text-slate-500">1.000đ tương đương 1 credit cơ bản. Bonus được cộng theo từng gói.</p></div><CreditPackageGrid packages={catalog?.packages || []} selectedId={customSelected ? '' : selectedId} onSelect={(id) => { setSelectedId(id); setCustomSelected(false); }} /><CustomTopupForm value={custom} selected={customSelected} onSelect={() => { setCustomSelected(true); setSelectedId(''); }} onChange={setCustom} />{customSelected && custom && !customValid && <p role="alert" className="text-sm font-semibold text-rose-600">Số tiền phải từ 10.000đ đến 50.000.000đ và chia hết cho 1.000đ.</p>}
      <fieldset><legend className="mb-3 text-sm font-bold text-slate-800">Cổng thanh toán</legend><div className="flex flex-wrap gap-3">{(['VNPAY', 'MOMO'] as const).map((item) => <label key={item} className={`flex min-w-36 items-center gap-3 rounded-xl border px-4 py-3 ${gateway === item ? 'border-secondary bg-sky-50' : 'border-slate-200 bg-white'} ${catalog?.gateways[item] ? 'cursor-pointer' : 'cursor-not-allowed opacity-45'}`}><input type="radio" name="gateway" value={item} disabled={!catalog?.gateways[item]} checked={gateway === item} onChange={() => setGateway(item)} /><span className="font-bold">{item === 'VNPAY' ? 'VNPay' : 'MoMo'}</span></label>)}</div></fieldset>
      <div className="flex flex-col justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-5 sm:flex-row sm:items-center"><div><span className="text-xs font-bold uppercase tracking-wider text-slate-500">Bạn sẽ nhận</span><strong className="block text-2xl text-primary">{estimated} credit</strong></div><button type="button" disabled={!canSubmit} onClick={checkout} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-6 py-3 font-bold text-white transition hover:bg-secondary disabled:cursor-not-allowed disabled:opacity-45">{submitting ? <LoaderCircle className="animate-spin" size={18} /> : <CreditCard size={18} />} {submitting ? 'Đang tạo thanh toán…' : 'Thanh toán an toàn'}</button></div><p className="flex items-center gap-2 text-xs text-slate-500"><ShieldCheck size={15} className="text-emerald-600" /> Credit chỉ được cộng sau callback có chữ ký hợp lệ từ cổng thanh toán.</p></section>
    <section className="space-y-4 rounded-3xl border border-slate-200 bg-white p-5 sm:p-7"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><h2 className="flex items-center gap-2 text-xl font-black text-slate-900"><History size={20} /> Lịch sử credit</h2><select aria-label="Lọc loại giao dịch" value={type} onChange={(event) => { const next = event.target.value; setType(next); setPage(1); void loadLedger(1, next); }} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">Tất cả giao dịch</option><option value="TOPUP">Nạp credit</option><option value="SETTLE">AI đã dùng</option><option value="RELEASE">Hoàn credit</option><option value="ADJUSTMENT">Điều chỉnh</option></select></div><CreditLedgerTable entries={entries} /><Pagination page={page} totalPages={totalPages} onPageChange={async (next) => { setPage(next); await loadLedger(next); }} /></section>
  </div>;
}
