/* oxlint-disable unicorn/no-thenable */
import Joi from 'joi';
import type { RequestValidationSchema } from '../middlewares/validate.js';
import { commonMessages, idParams, nonEmptyPatch, objectId, paginationQuery } from './commonValidator.js';

export const calculateNutritionSchema: RequestValidationSchema = { body: Joi.object({ weight: Joi.number().min(20).max(400).required(), height: Joi.number().min(80).max(250).required(), age: Joi.number().min(12).max(100).required(), mealCount: Joi.number().integer().min(1).max(10).default(3), gender: Joi.string().valid('male', 'female'), activityLevel: Joi.string().valid('sedentary', 'light', 'moderate', 'active', 'very_active'), timeframe: Joi.string().valid('1_day', '1_week', '1_month') }).messages(commonMessages) };
export const mealImageSchema: RequestValidationSchema = { query: Joi.object({ prompt: Joi.string().max(500), items: Joi.string().max(1000), seed: Joi.number().integer().min(0) }).messages(commonMessages) };
export const scanInbodySchema: RequestValidationSchema = { body: Joi.object({ imageBase64: Joi.string().min(100).required() }).messages(commonMessages) };
export const nutritionMetricsSchema: RequestValidationSchema = { body: Joi.object({ sex: Joi.string().valid('MALE', 'FEMALE').required(), weightKg: Joi.number().min(20).max(400).required(), heightCm: Joi.number().min(80).max(250).required(), age: Joi.number().min(12).max(100).required(), activityFactor: Joi.number().min(1).max(3).required(), goal: Joi.string().valid('FAT_LOSS', 'MAINTAIN', 'MUSCLE_GAIN').required() }).messages(commonMessages) };
export const createFormulaSchema: RequestValidationSchema = { body: Joi.object({ name: Joi.string().valid('MIFFLIN_ST_JEOR').required(), fatLossFactor: Joi.number().positive().max(5).required(), muscleGainFactor: Joi.number().positive().max(5).required(), proteinPerKg: Joi.number().positive().max(5).required(), fatPerKg: Joi.number().positive().max(5).required(), version: Joi.number().integer().min(1), active: Joi.boolean() }).messages(commonMessages) };
const macros = Joi.object({ protein: Joi.number().min(0).max(2000), carbs: Joi.number().min(0).max(2000), fat: Joi.number().min(0).max(2000) }).messages(commonMessages);
const logFields = { loggedAt: Joi.date().iso(), type: Joi.string().valid('FOOD', 'ACTIVITY'), name: Joi.string().trim(), calories: Joi.number().min(0).max(10000), macros, durationMinutes: Joi.number().min(1).max(1440), notes: Joi.string().allow('') };
export const listNutritionLogsSchema: RequestValidationSchema = { query: Joi.object({ ...paginationQuery, customerId: objectId.required(), from: Joi.date().iso(), to: Joi.date().iso(), type: Joi.string().valid('FOOD', 'ACTIVITY') }).messages(commonMessages) };
export const createNutritionLogSchema: RequestValidationSchema = { body: Joi.object({ customerId: objectId.required(), loggedAt: logFields.loggedAt.required(), type: logFields.type.required(), name: logFields.name.required(), calories: logFields.calories.required(), macros, durationMinutes: Joi.when('type', { is: 'ACTIVITY', then: Joi.number().min(1).max(1440).required(), otherwise: Joi.number().min(1).max(1440) }), notes: logFields.notes }).messages(commonMessages) };
export const updateNutritionLogSchema: RequestValidationSchema = { params: idParams(), body: nonEmptyPatch({ ...logFields, customerId: Joi.forbidden(), ptId: Joi.forbidden() }) };
export const nutritionLogIdSchema: RequestValidationSchema = { params: idParams() };
export const listActivitiesSchema: RequestValidationSchema = { query: Joi.object({ ...paginationQuery, keyword: Joi.string().allow(''), category: Joi.string(), active: Joi.boolean() }).messages(commonMessages) };
export const createActivitySchema: RequestValidationSchema = { body: Joi.object({ name: Joi.string().trim().required(), category: Joi.string().trim().required(), met: Joi.number().positive().max(30).required(), active: Joi.boolean() }).messages(commonMessages) };
export const updateActivitySchema: RequestValidationSchema = { params: idParams(), body: nonEmptyPatch({ name: Joi.string().trim(), category: Joi.string().trim(), met: Joi.number().positive().max(30), active: Joi.boolean() }) };
export const estimateActivitySchema: RequestValidationSchema = { params: idParams(), body: Joi.object({ weightKg: Joi.number().min(20).max(400).required(), durationMinutes: Joi.number().min(1).max(1440).required() }).messages(commonMessages) };
