import { useCallback, useEffect, useState } from 'react';
import CreditAdjustmentModal from '../../components/credits/CreditAdjustmentModal';
import CreditPackageAdmin, { type PackageDraft } from '../../components/credits/CreditPackageAdmin';
import CreditPricingPanel from '../../components/credits/CreditPricingPanel';
import CreditReconciliationTabs from '../../components/credits/CreditReconciliationTabs';
import { useToast } from '../../components/ui/ToastProvider';
import { creditsService } from '../../services/credits';
import { errorMessage } from '../../types';
import type { CreditPackage, CreditPricingAdmin } from '../../types/credits';
export default function CreditAdminPage() { const toast = useToast(); const [pricing, setPricing] = useState<CreditPricingAdmin | null>(null); const [packages, setPackages] = useState<CreditPackage[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const load = useCallback(async () => { const [nextPricing, nextPackages] = await Promise.all([creditsService.adminPricing(), creditsService.adminPackages()]); setPricing(nextPricing); setPackages(nextPackages); }, []); useEffect(() => { load().catch((error) => toast.error(errorMessage(error))).finally(() => setLoading(false)); }, [load, toast]); if (loading) return <div className="space-y-4"><div className="h-44 animate-pulse rounded-3xl bg-slate-200" /><div className="h-64 animate-pulse rounded-3xl bg-slate-200" /></div>; if (!pricing) return <div role="alert" className="rounded-2xl bg-rose-50 p-5 text-rose-700">Không thể tải cấu hình credit.</div>; const createPackage = async (draft: PackageDraft) => { try { await creditsService.createAdminPackage(draft); await load(); toast.success('Đã tạo gói credit.'); } catch (error) { toast.error(errorMessage(error)); } }; return <div className="mx-auto flex max-w-7xl flex-col gap-8 pb-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="text-xs font-bold uppercase tracking-[0.2em] text-secondary">Financial controls</span><h1 className="mt-2 text-3xl font-black text-slate-900">Quản trị credit</h1><p className="mt-1 text-sm text-slate-500">Định giá AI, gói nạp, đối soát và điều chỉnh có audit.</p></div><CreditAdjustmentModal onSubmit={async (input) => { await creditsService.adjust(input); toast.success('Đã điều chỉnh credit.'); }} /></div><CreditPricingPanel value={pricing} saving={saving} onChange={setPricing} onSave={async () => { setSaving(true); try { setPricing(await creditsService.updateAdminPricing(pricing)); toast.success('Đã lưu cấu hình credit.'); } catch (error) { toast.error(errorMessage(error)); } finally { setSaving(false); } }} /><CreditPackageAdmin packages={packages} onCreate={createPackage} onDelete={async (id) => { await creditsService.deleteAdminPackage(id); await load(); toast.success('Đã xóa gói credit.'); }} /><CreditReconciliationTabs /></div>; }
