const ERROR_CODES = Object.freeze({
  VALIDATION: 'VALIDATION_ERROR', INVALID_JSON: 'INVALID_JSON', AUTHENTICATION: 'AUTHENTICATION_ERROR',
  AUTHORIZATION: 'AUTHORIZATION_ERROR', NOT_FOUND: 'RESOURCE_NOT_FOUND', ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  DUPLICATE: 'DUPLICATE_RESOURCE', PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE', UPLOAD: 'UPLOAD_ERROR',
  EXTERNAL: 'EXTERNAL_SERVICE_ERROR', UNAVAILABLE: 'SERVICE_UNAVAILABLE', INTERNAL: 'INTERNAL_SERVER_ERROR',
  FEATURE_DISABLED: 'FEATURE_DISABLED', INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
});

type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export { ERROR_CODES };
export type { ErrorCode };
